// Generic Barrel Perks
#define GENERIC_BARREL_FULLBORE
#define GENERIC_BARREL_POLYGONAL
#define GENERIC_BARREL_FLUTED

// Shotgun Barrel Perks
#define SHOTGUN_BARREL_RIFLED
#define SHOTGUN_BARREL_SMOOTHBORE
#define SHOTGUN_BARREL_SHROUD
